/** Key names for environment variables. */
export const ENV_KEY_VAPID_PUBLIC = "NEXT_PUBLIC_VAPID_PUBLIC_KEY";
export const ENV_KEY_VAPID_PRIVATE = "VAPID_PRIVATE_KEY";
export const ENV_KEY_DEV_EMAIL = "DEV_EMAIL";

export const ENV_KEY_PGSTRING = "PGSTRING";
export const ENV_KEY_PGPORT = "PGPORT";
export const ENV_KEY_PGHOST = "PGHOST";
export const ENV_KEY_PGUSER = "PGUSER";
export const ENV_KEY_PGPASSWORD = "PGPASSWORD";
export const ENV_KEY_PGDATABASE = "PGDATABASE";

export const ENV_KEY_ACTION_SECRET = "ACTION_SECRET";

export const ENV_KEY_WEBSITE_URL = "NEXT_PUBLIC_WEBSITE_URL";
export const ENV_KEY_SPLATNET_URL = "NEXT_PUBLIC_SPLATNET_URL";

export const ENV_KEY_GOOGLE_ANALYTICS = "NEXT_PUBLIC_GOOGLE_ANALYTICS_TAG";
