name: Fetch gear
on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
    # run every 10 minutes
jobs:
  fetch_gear:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch gear
        # Send a request to the server with a secret key for authentication
        run: |
          curl --request POST \
          --url 'https://splatnet-alerts.netlify.app/api/check-and-notify' \
          --header 'Authorization: ${{secrets.ACTION_KEY}}'
