name: Fetch gear
on:
  schedule:
    - cron: '3,8,13,18,23,28,33,38,43,48,53,58 * * * *'
    # run every 5 minutes
jobs:
  fetch_gear:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch gear
        # Send a request to the server with a secret key for authentication
        run: |
          curl --request POST \
          --url 'https://splatnet-alerts.netlify.app/api/check-and-notify' \
          --header 'Authorization: ${{secrets.ACTION_KEY}}'
